CMAKE_MINIMUM_REQUIRED( VERSION 3.3 FATAL_ERROR #[[
    Requiring 3.3+:
        IF( ... IN_LIST ... )
]] )

IF(
       NOT "${CMAKE_CURRENT_LIST_DIR}/CMakeModules/" IN_LIST CMAKE_MODULE_PATH
    OR NOT "${CMAKE_CURRENT_LIST_DIR}/CMakeModules"  IN_LIST CMAKE_MODULE_PATH
)
    LIST( APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/CMakeModules/" )
ENDIF()
